version: '3'
services:
  pyspark:
    container_name: container_ingestao
    image: pyspark_image
    networks:
      - rede_projeto
    depends_on:
      - minio
    command: python3 /code/ingestao_dados.py

  minio:
    hostname: minio
    image: 'minio/minio:RELEASE.2021-01-08T21-18-21Z'
    container_name: minio
    ports:
      - '9000:9000'
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data
    networks:
      - rede_projeto

networks:
  rede_projeto: 
    name: rede_projeto
    driver: bridge